//
// Created by smilu97 on 21. 6. 27..
//

#ifndef KEYVALUE_COMMON_H
#define KEYVALUE_COMMON_H

#define PAGE_SIZE (0x1000)

#define BPTREE_HEADER_SIZE (128)

#define BPTREE_PAGE_TYPE_HEADER (0)
#define BPTREE_PAGE_TYPE_INTERNAL (1)
#define BPTREE_PAGE_TYPE_LEAF (2)

#endif //KEYVALUE_COMMON_H
